name:                ghcjs-dom-stub
version:             0.1.0.0
github:              "nishimura/ghcjs-dom-stub"
license:             BSD3
author:              "Satoshi Nishimura"
maintainer:          "nishim314@gmail.com"
copyright:           "Satoshi Nishimura"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nishimura/ghcjs-dom-stub#readme>

dependencies:
- base >= 4.7 && < 5

library:
  other-modules: []
  ghc-options: -Wall
  when:
  - condition: ! impl(ghcjs)
    source-dirs: src
